from concurrent.futures import ThreadPoolExecutor
from datetime import datetime, timedelta

import pytest

from app.core.errors import DocumentNotFound
from app.core.persistence import (
    PersistedModel,
    SqliteKvStore,
    _now_iso,
    configure_store,
    validate_id,
)


@pytest.fixture
def store():
    return SqliteKvStore(":memory:")


def test_write_then_read_roundtrips(store):
    store.write("run", "proj/1", {"status": "ok", "rows": 3})
    assert store.read("run", "proj/1") == {"status": "ok", "rows": 3}


def test_write_is_upsert(store):
    store.write("run", "proj/1", {"status": "running"})
    store.write("run", "proj/1", {"status": "ok"})
    assert store.read("run", "proj/1") == {"status": "ok"}


def test_concurrent_writers_all_land(store):
    """One `SqliteKvStore` holds ONE sqlite connection shared by every caller
    (`check_same_thread=False`), and a run writes from worker threads (the row
    driver's `parallelism`). Interleaved `execute`+`commit` on a shared
    connection loses rows and raises `OperationalError: cannot commit - no
    transaction is active`, so the store serializes them itself."""
    writers, per_writer = 8, 25

    def write_many(writer: int) -> None:
        for n in range(per_writer):
            store.write("run", f"proj/{writer}-{n}", {"writer": writer, "n": n})

    with ThreadPoolExecutor(max_workers=writers) as pool:
        for future in [pool.submit(write_many, w) for w in range(writers)]:
            future.result()

    assert len(store.list_ids("run", "proj/")) == writers * per_writer


def test_concurrent_readers_and_writers_see_consistent_rows(store):
    """A reader running against the same shared connection as a writer must get
    a whole row or nothing — never a torn scan or a cursor error."""
    store.write("run", "proj/seed", {"status": "ok"})

    def write_many(writer: int) -> None:
        for n in range(50):
            store.write("run", f"proj/{writer}-{n}", {"writer": writer})

    def read_many(_reader: int) -> None:
        for _ in range(50):
            assert store.read("run", "proj/seed") == {"status": "ok"}
            store.list_ids("run", "proj/")

    with ThreadPoolExecutor(max_workers=8) as pool:
        futures = [pool.submit(write_many, w) for w in range(4)]
        futures += [pool.submit(read_many, r) for r in range(4)]
        for future in futures:
            future.result()


def test_read_missing_raises_document_not_found(store):
    with pytest.raises(DocumentNotFound):
        store.read("run", "proj/nope")


def test_schema_version_persisted(store):
    store.write("run", "proj/1", {"status": "ok"}, schema_version=4)
    assert store.schema_version("run", "proj/1") == 4


def test_exists_and_delete(store):
    assert store.exists("run", "proj/1") is False
    store.write("run", "proj/1", {"x": 1})
    assert store.exists("run", "proj/1") is True
    store.delete("run", "proj/1")
    assert store.exists("run", "proj/1") is False


def test_delete_missing_is_silent(store):
    store.delete("run", "proj/absent")  # no raise


def test_read_tolerant_missing_returns_none(store):
    assert store.read_tolerant("run", "proj/absent") is None


def test_read_tolerant_corrupt_returns_none(store):
    # White-box: write a non-JSON body straight past write()'s json.dumps.
    store._conn.execute(
        "INSERT INTO documents (collection, id, data) VALUES (?, ?, ?)",
        ("run", "proj/bad", "{not json"),
    )
    store._conn.commit()
    assert store.read_tolerant("run", "proj/bad") is None


def test_list_ids_scopes_by_prefix(store):
    store.write("run", "roldugin/1", {"n": 1})
    store.write("run", "roldugin/2", {"n": 2})
    store.write("run", "assad/1", {"n": 9})
    assert store.list_ids("run") == ["assad/1", "roldugin/1", "roldugin/2"]
    assert store.list_ids("run", "roldugin/") == ["roldugin/1", "roldugin/2"]


def test_read_all_yields_id_and_body(store):
    store.write("run", "p/1", {"n": 1})
    store.write("run", "p/2", {"n": 2})
    assert dict(store.read_all("run", "p/")) == {"p/1": {"n": 1}, "p/2": {"n": 2}}


def test_list_ids_empty_collection(store):
    assert store.list_ids("nothing") == []


class _Widget(PersistedModel):
    collection = "widget"
    name: str
    count: int = 0


@pytest.fixture
def configured():
    configure_store(SqliteKvStore(":memory:"))


def test_save_and_load(configured):
    _Widget(id="a", name="hi", count=2).save()
    got = _Widget.load("a")
    assert (got.name, got.count) == ("hi", 2)


def test_id_autogenerates_when_the_caller_gives_none(configured):
    widget = _Widget(name="hi")

    assert widget.id
    widget.save()
    assert _Widget.load(widget.id).name == "hi"


def test_autogenerated_ids_are_distinct(configured):
    assert _Widget(name="a").id != _Widget(name="b").id


def test_a_caller_supplied_id_still_wins(configured):
    """read_all/list select by id prefix, so a findable record composes its own id."""
    _Widget(id="proj/one", name="x").save()
    _Widget(id="proj/two", name="y").save()
    _Widget(id="other/three", name="z").save()

    assert sorted(w.name for w in _Widget.list("proj/")) == ["x", "y"]


def test_two_records_written_in_the_same_second_order_deterministically(configured):
    """Newest-first reads sort on created_at, so back-to-back writes must not tie."""
    first = _Widget(name="first")
    second = _Widget(name="second")

    assert first.created_at != second.created_at
    assert first.created_at < second.created_at


def test_consecutive_stamps_strictly_increase():
    """The Windows wall clock ticks every ~15.6ms, so `datetime.now()` alone repeats."""
    stamps = [_now_iso() for _ in range(1000)]

    assert all(a < b for a, b in zip(stamps, stamps[1:]))


def test_concurrent_stampers_never_produce_the_same_stamp():
    """Threads share the last-stamp state, so an unguarded read-modify-write collides."""
    stampers, per_stamper = 8, 200

    def stamp_many(_stamper: int) -> list[str]:
        return [_now_iso() for _ in range(per_stamper)]

    with ThreadPoolExecutor(max_workers=stampers) as pool:
        stamps = [s for f in [pool.submit(stamp_many, n) for n in range(stampers)]
                  for s in f.result()]

    assert len(set(stamps)) == stampers * per_stamper


def test_load_or_none_missing(configured):
    assert _Widget.load_or_none("absent") is None


def test_list_returns_all_typed(configured):
    _Widget(id="a", name="x").save()
    _Widget(id="b", name="y").save()
    names = sorted(w.name for w in _Widget.list())
    assert names == ["x", "y"]


def test_delete_and_exists(configured):
    _Widget(id="a", name="x").save()
    assert _Widget.exists("a") is True
    _Widget.delete("a")
    assert _Widget.exists("a") is False


def test_get_store_unconfigured_raises():
    import app.core.persistence as p
    p._store = None
    with pytest.raises(RuntimeError):
        p.get_store()


@pytest.mark.parametrize(
    "id_",
    ["abc", "roldugin/20260710T142200", "a/b/c", "a.b-c_d"],
)
def test_validate_id_accepts_safe_ids(id_):
    assert validate_id(id_) == id_


@pytest.mark.parametrize(
    "id_",
    [
        "",
        " x",
        "/abs",
        "a\\b",
        "..",
        "a/../b",
        "a//b",
        "a/",
        "x\x00y",
        "C:/evil",  # POSIX-style drive-absolute id
        "C:\\evil",  # Windows-style drive-absolute id
        "C:evil",  # drive-relative id (no root); anchors to whatever drive is current
    ],
)
def test_validate_id_rejects_unsafe_ids(id_):
    with pytest.raises(ValueError):
        validate_id(id_)


def test_fresh_construct_stamps_created_and_updated_to_now(configured):
    before = datetime.now()
    w = _Widget(id="a", name="hi")
    after = datetime.now()
    created = datetime.fromisoformat(w.created_at)
    updated = datetime.fromisoformat(w.updated_at)
    assert w.created_at == w.updated_at
    assert before - timedelta(seconds=1) <= created <= after + timedelta(seconds=1)
    assert before - timedelta(seconds=1) <= updated <= after + timedelta(seconds=1)


def test_save_advances_updated_at_but_not_created_at(configured):
    # A known past created_at survives a save, while updated_at re-stamps to now
    # on every call — proving the base class, not the caller, owns the stamping.
    past = "2020-01-01T00:00:00"
    w = _Widget(id="a", name="hi", created_at=past, updated_at=past)
    w.save()
    assert w.created_at == past
    assert w.updated_at != past
    reloaded = _Widget.load("a")
    assert reloaded.created_at == past
    assert reloaded.updated_at != past


def test_load_of_a_record_without_timestamps_fills_defaults_via_factory(configured):
    # An OLD stored record written before created_at/updated_at existed carries
    # no such keys. extra="forbid" must still accept it on load: absent field +
    # default_factory means the factory supplies a value rather than raising.
    from app.core.persistence import get_store
    get_store().write("widget", "legacy", {"id": "legacy", "name": "old"})
    w = _Widget.load("legacy")
    assert w.created_at
    assert w.updated_at


def test_persistedmodel_config_mirrors_base():
    # PersistedModel deliberately does not import app.models._Base (the
    # store stays free of a models dependency), but its model_config is meant
    # to mirror it exactly. Nothing else enforces that — silent drift here
    # would change on-disk serialization — so pin it down explicitly.
    from app.models.schema import _Base
    from app.core.persistence import PersistedModel
    for key in ("extra", "use_enum_values", "validate_default", "populate_by_name"):
        assert PersistedModel.model_config.get(key) == _Base.model_config.get(key)
