// Every number here is traced in the Sources block of index.html. Nothing is estimated.
window.CLAIMS = [
{
  id: "doccs-terminated",
  project: "doccs_restrained",
  run: "20260903T141208.666644",
  stage: "figure5_counts",
  value: "5.8%",
  label: "Inmate-abuse cases that ended in dismissal",
  coverage: "closed",
  context: "cases initiated Jan 2000 – Oct 2020",
  sentence: ["A vast majority", " of ", "guards", " ", "accused of inmate abuse", " were ", "never terminated", "."],
  phrases: [0, 2, 4, 6],
  qualifiers: ["Read from the post-disposition penalty, not the penalty the department sought."],
  lede: "The reading of the penalty field is settled by the sentence itself and is not the weak point. Two things are: the outcome is missing on 28% of records, and the claim says guards where the file can only count cases.",
  stages: [
    ["cases", "input", "9,806 rows read from the Times' CSV"],
    ["rank_lookup", "input", "every TITLE spelling → one of four ranks, or blank"],
    ["cases_covered", "filter", "keep the four covered ranks"],
    ["cases_flagged", "row function", "inmate abuse = any code is IA"],
    ["ia_cases", "filter", "the inmate-abuse subset"],
    ["penalty_lookup", "input", "PENALTYDIS text → dismissal / ambiguous"],
    ["ia_job_status", "row function", "lost_job · kept_job · needs_review · unknown"],
    ["job_status_review", "review queue", "a journalist settles 18 ambiguous dispositions"],
    ["figure5_counts", "aggregate", "count by final job status"]
  ],
  shared_stages: {"rank_lookup": 3, "cases_covered": 3, "cases_flagged": 3, "ia_cases": 1},
  challenges: [
    {id:"d1", cls:"choice", phrase:6, stage:"penalty_lookup", settled:true,
     text:"Read PENALTY instead of PENALTYDIS. PENALTY is the penalty the department sought and reads DISMISSAL & ACCRUALS on 49% of guard records.",
     evidence:"59.5% terminated under PENALTY against 5.8% under PENALTYDIS. DISPO explains the gap: 4,522 settled, 835 went to award, 590 resigned, 356 withdrawn.",
     moves:{kind:"moves", detail:"5.8% → 59.5%. Reverses the sentence."}, cost:"settled",
     settled_by:"The published sentence is only true of PENALTYDIS. The methodology says so and the run reads it.",
     raised:"the methodology note"},
    {id:"d2", cls:"coverage", phrase:0, stage:"ia_job_status",
     text:"PENALTYDIS is blank on 28% of records. A blank is an unknown outcome, not a kept job.",
     evidence:"'Never terminated' is at most 94%, and 5.8% is the share of all cases, including the ones whose outcome the file does not hold.",
     moves:{kind:"moves", detail:"Turns the figure into a bound. The share among cases with a known outcome is not on the page."}, cost:"free",
     qualifier:"The outcome is missing on 28% of records. They count as unknown, not as kept jobs."},
    {id:"d3", cls:"choice", phrase:6, stage:"job_status_review",
     text:"Resigning under charges. The lookup sends a resignation to the journalist rather than calling it either way.",
     evidence:"590 cases in the file ended in resignation. In the inmate-abuse subset, 18 dispositions read as a resignation or a range and are queued; 0 of 18 were settled when this run was read.",
     moves:{kind:"moves", detail:"At most 18 cases upward if a resignation counts as losing the job."}, cost:"person",
     raised:"the methodology: 'a question for the reporter'",
     qualifier:"A resignation under charges is counted as ___. 18 cases turn on it."},
    {id:"d4", cls:"semantic", phrase:2, stage:"figure5_counts",
     text:"The sentence says guards. The run counts cases.",
     evidence:"s_GUID and SSNUMBER are empty on all 9,806 rows. A guard with three cases is three rows; two guards sharing a name are one.",
     moves:{kind:"meaning", detail:"Cannot be priced from this file. Nothing in it keys a person."}, cost:"outside",
     alt:{replace:{2:"inmate-abuse cases"}, join:{1:" of ", 3:" that ", 4:"", 5:"", 6:"ended without a dismissal"}, label:"Inmate-abuse cases that ended without a dismissal", value:"at most 94%",
          note:"The same count, said of cases. It drops the word the file cannot support."},
     qualifier:"Counts cases, not guards. The file carries no person key."},
    {id:"d5", cls:"semantic", phrase:4, stage:"cases_flagged",
     text:"Inmate abuse means any record carrying code IA. That reading gives 7.6% of investigations where The Times published 10.",
     evidence:"Either a choice upstream differs, the share runs over a different denominator, or The Times counted abuse from more than the IA code. This figure's denominator moves with whichever it is.",
     moves:{kind:"unpriced", detail:"Not a number until a person says which reading is right."}, cost:"person", raised:"the methodology note"},
    {id:"d6", cls:"omission", phrase:4, stage:"cases",
     text:"The note bounds the window by initiation and closing dates and names no field. The file has five.",
     evidence:"INVESDT, INCIDENTDT, FILECREATE, CLOSED, PERCLOSEDT. Which one the run reads, and how many rows the other four would admit or drop, has not been counted.",
     moves:{kind:"unpriced", detail:"A free rerun per field prices it."}, cost:"free"},
    {id:"d7", cls:"coverage", phrase:2, stage:"rank_lookup",
     text:"Match the four ranks exactly instead of every spelling.",
     evidence:"9,505 cases against 9,543. Both round to about 9,500; the share moves by less than a published digit.",
     moves:{kind:"none", detail:"Below published precision."}, cost:"free"},
    {id:"d8", cls:"data", phrase:4, stage:"cases",
     text:"Redactions leave no mark in the CSV.",
     evidence:"23 redacted descriptions, 0.33% of those carrying one. None falls in an inmate-abuse record.",
     moves:{kind:"none", detail:"Does not touch this figure's population."}, cost:"free"},
    {id:"d9", cls:"data", phrase:4, stage:"cases",
     text:"The CSV is a machine reading of a 60-page PDF, and The Times says the PDF is the authority.",
     evidence:"A second extraction finds the same 9,806 records and the same 725 inmate-abuse records. 204 of 509,912 cells differ, the inspected ones faults in the second reading.",
     moves:{kind:"none", detail:"Checked against the source."}, cost:"free"}
  ]
},
{
  id: "lda-outside-spend",
  project: "ai_lobbying_spend_2026",
  run: "20260901T103753.789399",
  stage: "ai_spend_totals",
  value: "$63,027,729",
  label: "Paid to outside firms to lobby on AI, in dollars",
  coverage: "closed",
  context: "Q1–Q2 2026",
  sentence: ["Clients paid outside firms ", "$63.0m", " ", "to lobby on AI", " in the ", "first half of 2026", "."],
  phrases: [1, 3, 5],
  qualifiers: ["Counts only lobbying that was filed."],
  lede: "One decision the code never made moves a published digit: nothing reads the client's country, so foreign clients are in by default. The one processing defect found does not touch this figure. It moves the in-house one.",
  stages: [
    ["lda_q1", "input", "US Senate LDA export, Q1 2026"],
    ["lda_q2", "input", "US Senate LDA export, Q2 2026"],
    ["corpus_totals", "aggregate", "45,061 rows · 42,918 filings"],
    ["paid_or_in_house", "row function", "registrant == client → in-house; income → paid"],
    ["ai_spend_totals", "aggregate", "sum of income over paid AI filings"]
  ],
  shared_stages: {"lda_q1": 4, "lda_q2": 4, "corpus_totals": 1, "paid_or_in_house": 1},
  challenges: [
    {id:"l1", cls:"omission", phrase:1, stage:"paid_or_in_house",
     text:"No branch reads client_country, so foreign clients are in by default. Nobody chose to include them.",
     evidence:"US clients alone: $61,447,729. 25 filings across 10 countries carry the difference, 2.5% of the money. 8 of them are '* Undetermined', $500,000, which a != 'USA' test would call foreign.",
     moves:{kind:"moves", detail:"$63.0m → $61.4m. The second published digit."}, cost:"free",
     raised:"nobody. The column is read by no arm of the code.",
     alt:{replace:{0:"US clients paid outside firms ", 1:"$61.4m"}, label:"Paid by US clients to outside firms to lobby on AI", value:"$61,447,729",
          note:"'US companies' AI lobbying' and 'AI lobbying of Congress by anyone' are different figures. Both are in the data."},
     qualifier:"Includes clients of every country. US clients alone account for $61.4m."},
    {id:"l2", cls:"coverage", phrase:5, stage:"lda_q2",
     text:"The shape says closed, and the export is a snapshot. Amendments to a Q2 filing can arrive after the pull.",
     evidence:"The run's own history holds the case: an earlier version counted each amended filing at its first value rather than its final one, and its $1,703,875 claim was superseded.",
     moves:{kind:"unpriced", detail:"A later export prices it."}, cost:"outside",
     qualifier:"Read from the export of ___. Filings amended after that date are at their earlier value."},
    {id:"l3", cls:"data", phrase:1, stage:"paid_or_in_house",
     text:"registrant == client is exact string equality, and the export spells one organisation two ways.",
     evidence:"TENABLE INC vs TENABLE, INC. 86 filings failed the test and were classed as paid. Those filings report no income, so this figure is unchanged. The in-house figure misses $86,739,976, understated by 25%.",
     moves:{kind:"none", detail:"Moves the in-house claim, not this one."}, cost:"free", cross:"in_house_ai_totals"},
    {id:"l4", cls:"gap", phrase:3, stage:"ai_spend_totals",
     text:"The rule that decides a filing is about AI was not probed.",
     evidence:"Nothing here says whether that rule is narrow or wide. It is the largest unexamined decision behind this figure.",
     moves:{kind:"unpriced", detail:"Not examined."}, cost:"free"}
  ]
},
{
  id: "compas-fpr",
  project: "compas_machine_bias",
  run: "20260902T134800",
  stage: "fpr_by_race",
  value: "1.92",
  label: "Black defendants' false-positive rate over white defendants'",
  coverage: "closed",
  context: "Broward County · 2013–14 intake · n = 6,172",
  sentence: ["Black defendants", " were ", "twice as likely", " to be ", "falsely flagged", " as ", "future criminals", "."],
  phrases: [0, 2, 4, 6],
  qualifiers: ["High risk means a COMPAS score above Low, roughly decile 5 and up."],
  lede: "Every alternative specification but one moves the ratio up, as far as 2.93. The famous data error does not touch it. The challenge that cannot be settled by a rerun is definitional: by predictive value, the same data reads as near-even, and the two cannot both be equal when base rates differ.",
  stages: [
    ["compas_scores", "input", "7,214 pretrial defendants, Broward County"],
    ["screening_window", "filter", "drop rows where arrest and screening are > 30 days apart · 1,042 dropped"],
    ["two_year_window", "filter", "two-year observation window"],
    ["race_pair", "filter", "African-American and Caucasian only"],
    ["high_risk", "row function", "high = score_text != Low"],
    ["fpr_by_race", "aggregate", "false-positive rate per group, ratio"]
  ],
  shared_stages: {"compas_scores": 2, "screening_window": 2, "two_year_window": 2, "race_pair": 2, "high_risk": 1},
  challenges: [
    {id:"c1", cls:"choice", phrase:2, stage:"high_risk",
     text:"Cut the decile somewhere else. The vendor's own manual treats a score as high from decile 7.",
     evidence:"≥ 4: 1.63 · as published: 1.92 · ≥ 7: 2.75 · ≥ 8: 2.93. Only the least defensible cut weakens it.",
     moves:{kind:"moves", detail:"1.63 to 2.93. Mostly stronger."}, cost:"free", raised:"Northpointe disputed the binarisation",
     qualifier:"At other risk cuts the ratio runs 1.63 to 2.93. The published cut is near the low end."},
    {id:"c2", cls:"semantic", phrase:4, stage:"fpr_by_race",
     text:"Measure the other error. Of those labelled high risk, 65.0% of Black and 59.5% of white defendants reoffended.",
     evidence:"Both numbers are correct at once. Chouldechova 2017: equal false-positive rates and equal predictive values cannot both hold when base rates differ, and they do: 52.3% vs 39.1%.",
     moves:{kind:"meaning", detail:"By predictive value the tool is near-even. The sentence reverses without a number changing."}, cost:"editorial",
     raised:"Flores, Bechtel & Lowenkamp 2016; Northpointe's rebuttal",
     alt:{replace:{0:"Among defendants labelled high risk, Black and white defendants", 2:"reoffended at similar rates", 4:"65.0% and 59.5%"}, join:{1:" ", 3:", ", 5:"", 6:""},
          label:"Positive predictive value, Black over white", value:"1.09",
          note:"The rebuttal's claim. Adopting it beside the first says which fairness definition the story asserts."},
     qualifier:"Compares false-positive rates. By predictive value the two groups are near-even (65.0% vs 59.5%)."},
    {id:"c3", cls:"semantic", phrase:6, stage:"two_year_window",
     text:"two_year_recid records re-arrest within two years. Not conviction, not offending.",
     evidence:"If policing is unequal, the label carries the bias being measured, on both sides of the argument. Nothing in the data settles it.",
     moves:{kind:"unpriced", detail:"Needs conviction records or victimisation surveys."}, cost:"outside",
     raised:"the objection both ProPublica and Northpointe are exposed to",
     qualifier:"'Reoffended' means re-arrested within two years."},
    {id:"c4", cls:"coverage", phrase:0, stage:"race_pair",
     text:"The claim compares two groups. 894 defendants are in the data and in no published figure.",
     evidence:"Hispanic 509 · Other 343 · Asian 31 · Native American 11.",
     moves:{kind:"unpriced", detail:"A scope fact. The story never claims otherwise."}, cost:"free",
     qualifier:"Compares Black and white defendants only. 894 others are in the data and not in this figure."},
    {id:"c5", cls:"data", phrase:6, stage:"two_year_window",
     text:"The two-year window was applied to non-recidivists but not to recidivists.",
     evidence:"Fixing it drops n to 5,304 and the base rate from 45.5% to 36.6%. The ratio stays 1.923 to three decimals; all 868 affected rows are recidivists and this rate is measured on non-recidivists. It moves predictive value instead, .650/.595 → .566/.491.",
     moves:{kind:"none", detail:"Moves the rebuttal's number, not this one."}, cost:"free", raised:"Barenstein 2019, arXiv:1906.04711", cross:"ppv_by_race"},
    {id:"c6", cls:"choice", phrase:0, stage:"screening_window",
     text:"The ±30-day screening filter, the only filter that drops anything.",
     evidence:"Swept from ±7 days to no limit: n 5,757–6,907, ratio 1.87–1.92.",
     moves:{kind:"none", detail:"Stable across the sweep."}, cost:"free", raised:"the filter most often called arbitrary"},
    {id:"c7", cls:"coverage", phrase:0, stage:"compas_scores",
     text:"One county, one intake. The headline is national.",
     evidence:"Broward was chosen because it released records at all. No other jurisdiction's scores are public.",
     moves:{kind:"unpriced", detail:"Another jurisdiction's scores."}, cost:"outside"},
    {id:"c8", cls:"semantic", phrase:4, stage:"high_risk",
     text:"The 137-question instrument and its weights are proprietary. Only the output decile is observed.",
     evidence:"Rudin et al 2018.",
     moves:{kind:"unpriced", detail:"The instrument. Never released."}, cost:"outside"}
  ]
}
];
